version: '3.9'
networks:
  postgresql:
  redis:
services:
  database:
    image: postgres:13.4
    volumes:
      - ./database_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgresql
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
  cache:
    image: redis:6.2.5
    networks:
      - redis
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot/
    networks:
      - postgresql
      - redis
    depends_on:
      - database
      - cache
    environment:
      TOKEN: "${TOKEN}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_TEST_HOST: "${DB_TEST_HOST}"
      DB_TEST_NAME: "${DB_TEST_NAME}"
      DB_TEST_PORT: "${DB_TEST_PORT}"
      DB_TEST_USER: "${DB_TEST_USER}"
      DB_TEST_PASS: "${DB_TEST_PASS}"
      DO_TESTS: "${DO_TESTS}"
